export const ICONS = {
  person: 'person',
  lock: 'lock-closed',
  eye: 'eye',
  eyeOff: 'eye-off',
  alertCircle: 'alert-circle',
  water: 'water',
  barbell: 'barbell',
  restaurant: 'restaurant',
  medkit: 'medkit',
  google: 'logo-google',
  facebook: 'logo-facebook',
  login: 'log-in',
  logout: 'log-out',
  logoutOutline: 'log-out-outline',
  key: 'key',
  home: 'home-outline',
  patients: 'people-outline',
  chat: 'chatbubble-ellipses-outline',
  user: 'person-circle-outline',
  planes: 'id-card-outline',
  download: 'download'
}
